#!/usr/bin/python3

import os
import unittest

import testvm  # from cockpit

# this is the minimal code to use Cockpit test VMs. For more advanced use
# cases, like deploying multiple machines, verbosity, etc., use cockpit's
# testlib.py.
class TestPinger(unittest.TestCase):
    def setUp(self):
        network = testvm.VirtNetwork(0)
        self.machine = testvm.VirtMachine(verbose=False,
                                          image=os.environ["TEST_IMAGE"],
                                          networking=network.host(),
                                          memory_mb=1024)
        self.machine.start()

    def tearDown(self):
        self.machine.stop()

    def test_installed(self):
        '''Check that cockpit-examples correctly installs pinger'''

        out = self.machine.execute("cockpit-bridge --packages")
        self.assertIn("pinger: /usr/share/cockpit/pinger", out)

if __name__ == '__main__':
    unittest.main()
